### ISSUE TITLE
Space after comment?

### ISSUE THREAD

**Issue by gopar** [rmuslimov/py-smart-operator#4]
This is more of a question. I know that this package is called `py-smart-operator`, (for operators) but would it be wise to add a space after a comment? I got used to the package handling all my spaces but I still have to do it manually for a comment.

I imagine a simple line just like the equal's would do this. (Haven't tried it, just guessing by the nature of `=`)
Something like this?

```
("#" py-smart-operator-do-nothing py-smart-operator-do-nothing py-smart-operator-do-wrap)
```

**Comment by rmuslimov** [comment]
Yep, I'm not sure that handling non-operators is our goal for now. I see many fixes required to do, before we can back to this question.
