### ISSUE TITLE
Unnecessary Spacing 

### ISSUE THREAD

**Issue by gopar** [rmuslimov/py-smart-operator#5]
More bugs! ha When trying to get an item in an array with a negative index it gives extra spacing. 
Ex:

``` python
a = [1, 2, 3, 4]
a[ - 1]  # Should be a[-1]
```

Same thing within dictionary

``` python
a = { - 1: "one"}  # Should be {-1: "one"}
```

**Comment by rmuslimov** [comment]
@gopar Seems like current implementation I chose - can't support this. I'll back with major refactoring later this year. Sorry for inconveniance
